jobs:
  build:
    name: Build and publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3.4.0
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      name: Cache SonarCloud packages
      uses: actions/cache@v3.3.1
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      id: gradle
      name: Build
      uses: eskatos/gradle-command-action@v2.3.3
      with:
        arguments: check
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        wrapper-cache-enabled: true
    - continue-on-error: true
      if: always()
      name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        junit_files: '**/test-results/**/*.xml'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      name: Analyze with SonarCloud
      uses: eskatos/gradle-command-action@v2.3.3
      with:
        arguments: sonarqube -Psonar.organization=resilience4j
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Publish to Sonatype
      uses: eskatos/gradle-command-action@v2.3.3
      with:
        arguments: publishToSonatype
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
  validation:
    name: Gradle wrapper validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3.4.0
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1.0.5
name: Build
on:
  repository_dispatch:
    types: trigger-ga___gradle-build.yml
